name: free
permissions:
  contents: write
on:
  schedule:
    - cron: "30 03 * * *"
  # push:
  #   branches: [main]
  workflow_dispatch:

# 设置上海时区
env:
  TZ: Asia/Shanghai

jobs:
  free:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.11.0
      - name: Install Dependencies
        run: yarn install
      - name: free
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          OK_USER: ${{ secrets.OK_USER }}
          OK_PASSWORD: ${{ secrets.OK_PASSWORD }}
        run: yarn run free
      - name: deploy
        # 使用github-pages-deploy-action: https://github.com/JamesIves/github-pages-deploy-action/tree/master
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          BRANCH: main # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/h7ml
          dst: gitee/h7ml
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          white_list: "okjiasu_action"
          force_update: true
          account_type: user
          clone_style: ssh
          debug: true
    needs: free
