name: check
permissions:
  contents: write
on:
  schedule:
    - cron: "00 04 * * *"
  # push:
  #   branches: [main]
  workflow_dispatch:

# 设置上海时区
env:
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.11.0
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: node-modules-
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: serve
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          OK_USER: ${{ secrets.OK_USER }}
          OK_PASSWORD: ${{ secrets.OK_PASSWORD }}
        run: yarn run serve
      - name: deploy
        # 使用github-pages-deploy-action: https://github.com/JamesIves/github-pages-deploy-action/tree/master
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          BRANCH: main # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
