name: okjiasu_action
permissions:
  contents: write
on:
  schedule:
    - cron: "00 08 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: node-modules-
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: serve
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          OK_USER: ${{ secrets.OK_USER }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: npm run serve
      - name: 更新数据
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: main
          folder: .
